# Don't edit this file
#
# It was auto generated by CMake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES napmath napscene napparameter napaudio)
set(DEEP_DEPENDENT_NAP_MODULES napmath napscene napparameter napaudio napcolor)
set(DEEP_DEPENDENT_RPATHS ../../../../system_modules/napaudio/thirdparty/mpg123/msvc/x86_64/lib ../../../../system_modules/napaudio/thirdparty/portaudio/msvc/x86_64/lib ../../../../system_modules/napaudio/thirdparty/libsndfile/msvc/x86_64/lib)
